CoastalME (Coastal Modelling Environment): CGeomRasterGrid Class Reference
CGeomRasterGrid Class Reference
Geometry cass used to represent the raster grid of cell objects.
#include <raster_grid.h>
Public Member Functions
CGeomRasterGrid (CSimulation *)
~CGeomRasterGrid (void)
CSimulation * pGetSim (void)
int nCreateGrid (void)
Friends
class CSimulation
class CGeomProfile
Detailed Description
Geometry cass used to represent the raster grid of cell objects.
TODO This is a more detailed description of the CGeomRasterGrid class.
Author
David Favis-Mortlock
Andres Payo
Date
2020
Copyright
GNU General Public License
Definition at line 37 of file raster_grid.h.
Constructor & Destructor Documentation
CGeomRasterGrid()
CGeomRasterGrid::CGeomRasterGrid (CSimulation * pSimIn) explicit
Definition at line 32 of file raster_grid.cpp.
~CGeomRasterGrid()
CGeomRasterGrid::~CGeomRasterGrid (void)
Definition at line 42 of file raster_grid.cpp.
Member Function Documentation
nCreateGrid()
int CGeomRasterGrid::nCreateGrid (void)
Definition at line 66 of file raster_grid.cpp.
pGetSim()
CSimulation * CGeomRasterGrid::pGetSim (void)
Definition at line 54 of file raster_grid.cpp.
Referenced by CGeomCell::bBasementElevIsMissingValue(), CGeomCell::bIsInundated(), CGeomCell::bIsSeaIncBeach(), CGeomCell::CalcAllLayerElevsAndD50(), and CGeomCell::SetSeaDepth().
Friends And Related Function Documentation
CGeomProfile
friend class CGeomProfile friend
Definition at line 40 of file raster_grid.h.
CSimulation
friend class CSimulation friend
Definition at line 39 of file raster_grid.h.
The documentation for this class was generated from the following files:
raster_grid.h
raster_grid.cpp