CoastalME (Coastal Modelling Environment): CRWCellLandform Class Reference
CRWCellLandform Class Reference
Real-world class used to represent the landform of a cell.
#include <cell_landform.h>
Public Member Functions
CRWCellLandform ()
~CRWCellLandform (void)
void SetLFCategory (int const)
Set the landform category and initialise the sub-category.
int nGetLFCategory (void) const
Get the landform category.
void SetLFSubCategory (int const)
Set the both the landform sub-category, and the landform category.
int nGetLFSubCategory (void) const
Get the landform sub-category.
void SetCoast (int const)
Set the coast number.
int nGetCoast (void) const
Get the coast number.
void SetPointOnCoast (int const)
Set the number of the point on the coastline.
int nGetPointOnCoast (void) const
Set the number of the point on the coastline.
void SetAccumWaveEnergy (double const)
Set accumulated wave energy.
double dGetAccumWaveEnergy (void) const
Get accumulated wave energy.
void SetCliffNotchBaseElev (double const)
Set cliff notch base elevation.
double dGetCliffNotchBaseElev (void) const
Get cliff notch base elevation.
void SetCliffNotchOverhang (double const)
Set the cliff notch overhang which remains on this cell.
double dGetCliffNotchOverhang (void) const
Get the cliff notch overhang which remains on this cell.
void SetCliffRemaining (double const)
Set the cliff depth remaining on this cell.
double dGetCliffRemaining (void) const
Get the cliff depth remaining on this cell.
Detailed Description
Real-world class used to represent the landform of a cell.
TODO This is a more detailed description of the CCRWCellLandform class.
Author
David Favis-Mortlock
Andres Payo
Date
2021
Copyright
GNU General Public License
Definition at line 30 of file cell_landform.h.
Constructor & Destructor Documentation
CRWCellLandform()
CRWCellLandform::CRWCellLandform ()
Definition at line 29 of file cell_landform.cpp.
~CRWCellLandform()
CRWCellLandform::~CRWCellLandform (void)
Definition at line 38 of file cell_landform.cpp.
Member Function Documentation
dGetAccumWaveEnergy()
double CRWCellLandform::dGetAccumWaveEnergy (void) const
Get accumulated wave energy.
Definition at line 105 of file cell_landform.cpp.
dGetCliffNotchBaseElev()
double CRWCellLandform::dGetCliffNotchBaseElev (void) const
Get cliff notch base elevation.
Definition at line 117 of file cell_landform.cpp.
dGetCliffNotchOverhang()
double CRWCellLandform::dGetCliffNotchOverhang (void) const
Get the cliff notch overhang which remains on this cell.
Definition at line 129 of file cell_landform.cpp.
dGetCliffRemaining()
double CRWCellLandform::dGetCliffRemaining (void) const
Get the cliff depth remaining on this cell.
Definition at line 141 of file cell_landform.cpp.
nGetCoast()
int CRWCellLandform::nGetCoast (void) const
Get the coast number.
Definition at line 81 of file cell_landform.cpp.
nGetLFCategory()
int CRWCellLandform::nGetLFCategory (void) const
Get the landform category.
Definition at line 50 of file cell_landform.cpp.
Referenced by CGeomCell::nGetInterventionClass().
nGetLFSubCategory()
int CRWCellLandform::nGetLFSubCategory (void) const
Get the landform sub-category.
Definition at line 68 of file cell_landform.cpp.
Referenced by CGeomCell::nGetInterventionClass().
nGetPointOnCoast()
int CRWCellLandform::nGetPointOnCoast (void) const
Set the number of the point on the coastline.
Definition at line 93 of file cell_landform.cpp.
SetAccumWaveEnergy()
void CRWCellLandform::SetAccumWaveEnergy (double const dEnergyIn)
Set accumulated wave energy.
Definition at line 99 of file cell_landform.cpp.
SetCliffNotchBaseElev()
void CRWCellLandform::SetCliffNotchBaseElev (double const dElevIn)
Set cliff notch base elevation.
Definition at line 111 of file cell_landform.cpp.
SetCliffNotchOverhang()
void CRWCellLandform::SetCliffNotchOverhang (double const dLenIn)
Set the cliff notch overhang which remains on this cell.
Definition at line 123 of file cell_landform.cpp.
SetCliffRemaining()
void CRWCellLandform::SetCliffRemaining (double const dLenIn)
Set the cliff depth remaining on this cell.
Definition at line 135 of file cell_landform.cpp.
SetCoast()
void CRWCellLandform::SetCoast (int const nCoastIn)
Set the coast number.
Definition at line 75 of file cell_landform.cpp.
SetLFCategory()
void CRWCellLandform::SetLFCategory (int const nClassIn)
Set the landform category and initialise the sub-category.
Definition at line 43 of file cell_landform.cpp.
Referenced by CGeomCell::CGeomCell(), and CGeomCell::SetInterventionClass().
SetLFSubCategory()
void CRWCellLandform::SetLFSubCategory (int const nClassIn)
Set the both the landform sub-category, and the landform category.
Definition at line 56 of file cell_landform.cpp.
Referenced by CGeomCell::SetInterventionClass().
SetPointOnCoast()
void CRWCellLandform::SetPointOnCoast (int const nPointOnCoastIn)
Set the number of the point on the coastline.
Definition at line 87 of file cell_landform.cpp.
Field Documentation
m_dNotchBaseElev
double CRWCellLandform::m_dNotchBaseElev
Definition at line 53 of file cell_landform.h.
m_dNotchOverhang
double CRWCellLandform::m_dNotchOverhang
Definition at line 54 of file cell_landform.h.
m_dRemaining
double CRWCellLandform::m_dRemaining
Definition at line 55 of file cell_landform.h.
m_nDummy
int CRWCellLandform::m_nDummy
Definition at line 46 of file cell_landform.h.
struct { ... } CRWCellLandform::m_sBeachData
struct { ... } CRWCellLandform::m_sCliffData
The documentation for this class was generated from the following files:
cell_landform.h
cell_landform.cpp