CoastalME (Coastal Modelling Environment): CGeomCell Class Reference
CGeomCell Class Reference
Geometry class for the cell objects which comprise the raster grid.
#include <cell.h>
Public Member Functions
CGeomCell ()
~CGeomCell (void)
void SetInContiguousSea (void)
bool bIsInContiguousSea (void) const
void SetActualBeachErosionEstimated (void)
bool bGetActualBeachErosionEstimated (void) const
void SetInActiveZone (bool const)
Sets a flag to show whether this cell is in the active zone.
bool bIsInActiveZone (void) const
Returns a flag which shows whether this cell is in the active zone.
bool bPotentialPlatformErosion (void) const
Returns true if this cell has had potential erosion this timestep.
void SetAsCoastline (bool const)
Marks this cell as 'under' a coastline.
bool bIsCoastline (void) const
Returns true if the cell is 'under' a coastline.
void SetProfile (int const)
Marks this cell as 'under' a coastline-normal profile.
int nGetProfile (void) const
If this cell is 'under' a coastline-normal profile, returns the number of the profile. Otherwise it returns INT_NODATA.
bool bIsProfile (void) const
Returns true if this cell is 'under' a coastline normal.
void SetShadowZoneBoundary (void)
Sets a flag to show that this cell is a shadow zone boundary.
bool bIsShadowZoneBoundary (void) const
Returns a flag which shows whether this cell is a shadow zone boundary.
void SetBoundingBoxEdge (int const)
int nGetBoundingBoxEdge (void) const
bool bIsBoundingBoxEdge (void) const
void SetPossibleCoastStartCell (void)
Sets a flag to show that this cell has been flagged as a possible start- or end-point for a coastline.
bool bIsPossibleCoastStartCell (void) const
Returns a flag which shows whether this cell has been flagged as a possible start- or end-point for a coastline.
void SetPolygonID (int const)
Sets the global ID number of the polygon which 'contains' this cell.
int nGetPolygonID (void) const
Returns the global ID number of the polygon which 'contains' this cell (returns INT_NODATA if the cell is not 'in' a polygon)
CRWCellLandform * pGetLandform (void)
Returns a pointer to this cell's CRWCellLandform object.
void SetLocalConsSlope (double const)
Sets the local slope of the consolidated sediment only.
double dGetLocalConsSlope (void) const
Returns the local slope of the consolidated sediment only.
void SetBasementElev (double const)
Sets this cell's basement elevation.
double dGetBasementElev (void) const
Returns this cell's basement elevation.
bool bBasementElevIsMissingValue (void) const
Returns true if this cells's basement data is NODATA, is needed for irregularly-shaped DEMs.
double dGetVolEquivSedTopElev (void) const
Returns the volume-equivalent elevation of the sediment's top surface for this cell (if there is a cliff notch, then lower the elevation by the notch's volume)
double dGetSedimentTopElev (void) const
Returns the true elevation of the sediment's top surface for this cell (if there is a cliff notch, ignore the missing volume)
double dGetSedimentPlusInterventionTopElev (void) const
Returns the true elevation of the sediment's top surface for this cell (if there is a cliff notch, ignore the missing volume) plus the height of any intervention.
double dGetOverallTopElev (void) const
Returns the highest elevation of the cell, which is either the sediment top elevation plus intervention height, or the sea surface elevation.
bool bIsInundated (void) const
Returns true if the elevation of the sediment top surface for this cell (plus any intervention) is less than the grid's this-timestep still water elevation.
bool bIsSeaIncBeach (void) const
Returns true if the elevation of the sediment top surface for this cell is greater than or equal to the grid's this-timestep still water elevation. Also returns true if the cell has unconsolidated sediment on it and the elevation of the sediment top surface, minus a tolerance value, is less than the grid's this-timestep still water elevation.
void SetSeaDepth (void)
Returns the depth of seawater on this cell if the sediment top is < SWL, or zero.
double dGetSeaDepth (void) const
Returns the depth of seawater on this cell.
void InitCell (void)
Initialise several values for this cell.
double dGetTotSeaDepth (void) const
void SetWaveHeight (double const)
Sets the wave height on this cell, also increments the total wave height.
double dGetWaveHeight (void) const
Returns the wave height on this cell.
double dGetTotWaveHeight (void) const
Returns the total wave height on this cell.
void SetWaveOrientation (double const)
Sets the wave orientation on this cell, also increments the total wave orientation.
double dGetWaveOrientation (void) const
Returns the wave orientation on this cell.
double dGetTotWaveOrientation (void) const
Returns the total wave orientation on this cell.
void SetWavePeriod (double const)
double dGetWavePeriod (void) const
void SetDeepWaterWaveHeight (double const)
Sets the deep water wave height on this cell.
double dGetDeepWaterWaveHeight (void) const
Returns the deep water wave height on this cell.
void SetDeepWaterWaveOrientation (double const)
Sets the deep water wave orientation on this cell.
double dGetDeepWaterWaveOrientation (void) const
Returns the deep water wave orientation on this cell.
void SetDeepWaterWavePeriod (double const)
Sets the deep water wave Period on this cell.
double dGetDeepWaterWavePeriod (void) const
Returns the deep water wave period on this cell.
void SetWaveValuesToDeepWaterWaveValues (void)
Sets wave height to the deep water wave height value, and sets wave orientation to the deep water wave orientation value.
void SetBeachProtectionFactor (double const)
double dGetBeachProtectionFactor (void) const
Returns this cell's beach protection factor.
void SetSuspendedSediment (double const)
Sets this cell's suspended sediment depth equivalent, it also increments the running total of suspended sediment depth equivalent.
double dGetSuspendedSediment (void) const
Returns the suspended sediment depth equivalent on this cell.
double dGetTotSuspendedSediment (void) const
int nGetTopNonZeroLayerAboveBasement (void) const
Returns the index of the topmost sediment layer (layer 0 being the one just above basement) with non-zero thickness. If there is no such layer, it returns NO_NONZERO_THICKNESS_LAYERS.
int nGetTopLayerAboveBasement (void) const
Returns the index of the topmost sediment layer (layer 0 being the one just above basement), which could have zero thickness.
double dGetConsSedTopForLayerAboveBasement (int const) const
Returns the elevation of the top of the consolidated sediment only, for a given layer (layer 0 being the one just above basement)
CRWCellLayer * pGetLayerAboveBasement (int const)
Return a reference to the Nth sediment layer (layer 0 being just above basement)
void AppendLayers (int const)
Appends sediment layers.
void CalcAllLayerElevsAndD50 (void)
For this cell: calculates the elevation of the top of every layer, and the d50 for the topmost unconsolidated sediment layer.
int nGetLayerAtElev (double const) const
Given an elevation, this finds the index of the layer that contains that elevation (layer 0 being the first above the basement). Note that the elevation cannot exactly equal the elevation of the layer's top surface (this causes problems with e.g. cliff notches, which extend above this elevation)
double dCalcLayerElev (const int)
For this cell, calculates the elevation of the top of a given layer.
double dGetTotConsThickness (void) const
Returns the total thickness of consolidated sediment on this cell.
double dGetTotUnconsThickness (void) const
Returns the total thickness of unconsolidated sediment on this cell.
double dGetTotAllSedThickness (void) const
Returns the total thickness of all sediment on this cell.
void SetPotentialPlatformErosion (double const)
Set potential (unconstrained) shore platform erosion and increment total shore platform potential erosion.
double dGetPotentialPlatformErosion (void) const
Get potential (unconstrained) shore platform erosion.
double dGetTotPotentialPlatformErosion (void) const
Get total potential (unconstrained) shore platform erosion.
void SetActualPlatformErosion (double const)
Set this-timestep actual (constrained) shore platform erosion and increment total actual shore platform erosion.
double dGetActualPlatformErosion (void) const
Get actual (constrained) shore platform erosion.
double dGetTotActualPlatformErosion (void) const
Get total actual (constrained) shore platform erosion.
void IncrCliffCollapse (double const)
Increments the depth of this-timestep cliff collapse on this cell, also increments the total.
double dGetCliffCollapse (void) const
Returns the depth of this-timestep cliff collapse on this cell.
double dGetTotCliffCollapse (void) const
Returns the running total depth of cliff collapse on this cell.
void IncrCliffCollapseDeposition (double const)
Increments the depth of this-timestep cliff deposition collapse on this cell, also increments the total.
double dGetCliffCollapseDeposition (void) const
Retuns the depth of this-timestep cliff deposition collapse on this cell.
double dGetTotCliffCollapseDeposition (void) const
Returns the total depth of cliff deposition collapse on this cell.
void SetPotentialBeachErosion (double const)
Set potential (unconstrained) beach erosion and increment total beach potential erosion.
double dGetPotentialBeachErosion (void) const
Get potential (unconstrained) beach erosion.
double dGetTotPotentialBeachErosion (void) const
Get total potential (unconstrained) beach erosion.
void SetActualBeachErosion (double const)
Set this-timestep actual (constrained) beach erosion and increment total actual beach erosion.
double dGetActualBeachErosion (void) const
Get actual (constrained) beach erosion.
double dGetTotActualBeachErosion (void) const
Get total actual (constrained) beach erosion.
void IncrBeachDeposition (double const)
Increment this-timestep beach deposition, also increment total beach deposition.
double dGetBeachDeposition (void) const
Get beach deposition.
double dGetTotBeachDeposition (void) const
Get beach erosion.
bool bBeachErosionOrDepositionThisTimestep (void) const
Returns true only if this cell has had no deposition or erosion this timestep.
double dGetUnconsD50 (void) const
Returns the D50 of unconsolidated sediment on this cell.
void SetInterventionClass (int const)
Sets the landform category and subcategory for an intervention.
int nGetInterventionClass (void) const
Gets the intervention class.
void SetInterventionHeight (double const)
Sets the intervention height.
double dGetInterventionHeight (void) const
Returns the intervention height.
double dGetInterventionTopElev (void) const
Returns the elevation of the top of the intervention, assuming it rests on the sediment-top surface.
void SetShadowZoneNumber (int const)
int nGetShadowZoneNumber (void) const
bool bIsinThisShadowZone (int const) const
bool bIsinAnyShadowZone (void) const
void SetDownDriftZoneNumber (int const)
int nGetDownDriftZoneNumber (void) const
Static Public Attributes
static CGeomRasterGrid * m_pGrid = NULL
Friends
class CSimulation
Detailed Description
Geometry class for the cell objects which comprise the raster grid.
TODO This is a more detailed description of the CGeomCell class.
Author
David Favis-Mortlock
Andres Payo
Date
2020
Copyright
GNU General Public License
Definition at line 35 of file cell.h.
Constructor & Destructor Documentation
CGeomCell()
CGeomCell::CGeomCell ()
Definition at line 31 of file cell.cpp.
~CGeomCell()
CGeomCell::~CGeomCell (void)
Definition at line 76 of file cell.cpp.
Member Function Documentation
AppendLayers()
void CGeomCell::AppendLayers (int const nLayer)
Appends sediment layers.
Definition at line 458 of file cell.cpp.
Referenced by CSimulation::nDoSimulation().
bBasementElevIsMissingValue()
bool CGeomCell::bBasementElevIsMissingValue (void) const
Returns true if this cells's basement data is NODATA, is needed for irregularly-shaped DEMs.
Definition at line 286 of file cell.cpp.
bBeachErosionOrDepositionThisTimestep()
bool CGeomCell::bBeachErosionOrDepositionThisTimestep (void) const
Returns true only if this cell has had no deposition or erosion this timestep.
Definition at line 813 of file cell.cpp.
bGetActualBeachErosionEstimated()
bool CGeomCell::bGetActualBeachErosionEstimated (void) const
Definition at line 113 of file cell.cpp.
bIsBoundingBoxEdge()
bool CGeomCell::bIsBoundingBoxEdge (void) const
Definition at line 91 of file cell.cpp.
bIsCoastline()
bool CGeomCell::bIsCoastline (void) const
Returns true if the cell is 'under' a coastline.
Definition at line 176 of file cell.cpp.
bIsInActiveZone()
bool CGeomCell::bIsInActiveZone (void) const
Returns a flag which shows whether this cell is in the active zone.
Definition at line 126 of file cell.cpp.
bIsinAnyShadowZone()
bool CGeomCell::bIsinAnyShadowZone (void) const
Definition at line 234 of file cell.cpp.
bIsInContiguousSea()
bool CGeomCell::bIsInContiguousSea (void) const
Definition at line 102 of file cell.cpp.
bIsinThisShadowZone()
bool CGeomCell::bIsinThisShadowZone (int const nZone) const
Definition at line 226 of file cell.cpp.
bIsInundated()
bool CGeomCell::bIsInundated (void) const
Returns true if the elevation of the sediment top surface for this cell (plus any intervention) is less than the grid's this-timestep still water elevation.
Definition at line 408 of file cell.cpp.
bIsPossibleCoastStartCell()
bool CGeomCell::bIsPossibleCoastStartCell (void) const
Returns a flag which shows whether this cell has been flagged as a possible start- or end-point for a coastline.
Definition at line 152 of file cell.cpp.
bIsProfile()
bool CGeomCell::bIsProfile (void) const
Returns true if this cell is 'under' a coastline normal.
Definition at line 195 of file cell.cpp.
bIsSeaIncBeach()
bool CGeomCell::bIsSeaIncBeach (void) const
Returns true if the elevation of the sediment top surface for this cell is greater than or equal to the grid's this-timestep still water elevation. Also returns true if the cell has unconsolidated sediment on it and the elevation of the sediment top surface, minus a tolerance value, is less than the grid's this-timestep still water elevation.
Definition at line 414 of file cell.cpp.
bIsShadowZoneBoundary()
bool CGeomCell::bIsShadowZoneBoundary (void) const
Returns a flag which shows whether this cell is a shadow zone boundary.
Definition at line 139 of file cell.cpp.
bPotentialPlatformErosion()
bool CGeomCell::bPotentialPlatformErosion (void) const
Returns true if this cell has had potential erosion this timestep.
Definition at line 159 of file cell.cpp.
CalcAllLayerElevsAndD50()
void CGeomCell::CalcAllLayerElevsAndD50 (void)
For this cell: calculates the elevation of the top of every layer, and the d50 for the topmost unconsolidated sediment layer.
Definition at line 465 of file cell.cpp.
dCalcLayerElev()
double CGeomCell::dCalcLayerElev (const int nLayer)
For this cell, calculates the elevation of the top of a given layer.
Definition at line 514 of file cell.cpp.
dGetActualBeachErosion()
double CGeomCell::dGetActualBeachErosion (void) const
Get actual (constrained) beach erosion.
Definition at line 768 of file cell.cpp.
dGetActualPlatformErosion()
double CGeomCell::dGetActualPlatformErosion (void) const
Get actual (constrained) shore platform erosion.
Definition at line 552 of file cell.cpp.
dGetBasementElev()
double CGeomCell::dGetBasementElev (void) const
Returns this cell's basement elevation.
Definition at line 280 of file cell.cpp.
dGetBeachDeposition()
double CGeomCell::dGetBeachDeposition (void) const
Get beach deposition.
Definition at line 794 of file cell.cpp.
dGetBeachProtectionFactor()
double CGeomCell::dGetBeachProtectionFactor (void) const
Returns this cell's beach protection factor.
Definition at line 696 of file cell.cpp.
dGetCliffCollapse()
double CGeomCell::dGetCliffCollapse (void) const
Returns the depth of this-timestep cliff collapse on this cell.
Definition at line 710 of file cell.cpp.
dGetCliffCollapseDeposition()
double CGeomCell::dGetCliffCollapseDeposition (void) const
Retuns the depth of this-timestep cliff deposition collapse on this cell.
Definition at line 729 of file cell.cpp.
dGetConsSedTopForLayerAboveBasement()
double CGeomCell::dGetConsSedTopForLayerAboveBasement (int const nLayer) const
Returns the elevation of the top of the consolidated sediment only, for a given layer (layer 0 being the one just above basement)
Definition at line 352 of file cell.cpp.
dGetDeepWaterWaveHeight()
double CGeomCell::dGetDeepWaterWaveHeight (void) const
Returns the deep water wave height on this cell.
Definition at line 651 of file cell.cpp.
dGetDeepWaterWaveOrientation()
double CGeomCell::dGetDeepWaterWaveOrientation (void) const
Returns the deep water wave orientation on this cell.
Definition at line 663 of file cell.cpp.
dGetDeepWaterWavePeriod()
double CGeomCell::dGetDeepWaterWavePeriod (void) const
Returns the deep water wave period on this cell.
Definition at line 675 of file cell.cpp.
dGetInterventionHeight()
double CGeomCell::dGetInterventionHeight (void) const
Returns the intervention height.
Definition at line 865 of file cell.cpp.
dGetInterventionTopElev()
double CGeomCell::dGetInterventionTopElev (void) const
Returns the elevation of the top of the intervention, assuming it rests on the sediment-top surface.
Definition at line 871 of file cell.cpp.
dGetLocalConsSlope()
double CGeomCell::dGetLocalConsSlope (void) const
Returns the local slope of the consolidated sediment only.
Definition at line 267 of file cell.cpp.
dGetOverallTopElev()
double CGeomCell::dGetOverallTopElev (void) const
Returns the highest elevation of the cell, which is either the sediment top elevation plus intervention height, or the sea surface elevation.
Definition at line 401 of file cell.cpp.
dGetPotentialBeachErosion()
double CGeomCell::dGetPotentialBeachErosion (void) const
Get potential (unconstrained) beach erosion.
Definition at line 749 of file cell.cpp.
dGetPotentialPlatformErosion()
double CGeomCell::dGetPotentialPlatformErosion (void) const
Get potential (unconstrained) shore platform erosion.
Definition at line 533 of file cell.cpp.
dGetSeaDepth()
double CGeomCell::dGetSeaDepth (void) const
Returns the depth of seawater on this cell.
Definition at line 296 of file cell.cpp.
Referenced by CGeomProfile::nGetCellGivenDepth().
dGetSedimentPlusInterventionTopElev()
double CGeomCell::dGetSedimentPlusInterventionTopElev (void) const
Returns the true elevation of the sediment's top surface for this cell (if there is a cliff notch, ignore the missing volume) plus the height of any intervention.
Definition at line 395 of file cell.cpp.
dGetSedimentTopElev()
double CGeomCell::dGetSedimentTopElev (void) const
Returns the true elevation of the sediment's top surface for this cell (if there is a cliff notch, ignore the missing volume)
Definition at line 389 of file cell.cpp.
dGetSuspendedSediment()
double CGeomCell::dGetSuspendedSediment (void) const
Returns the suspended sediment depth equivalent on this cell.
Definition at line 315 of file cell.cpp.
dGetTotActualBeachErosion()
double CGeomCell::dGetTotActualBeachErosion (void) const
Get total actual (constrained) beach erosion.
Definition at line 774 of file cell.cpp.
dGetTotActualPlatformErosion()
double CGeomCell::dGetTotActualPlatformErosion (void) const
Get total actual (constrained) shore platform erosion.
Definition at line 558 of file cell.cpp.
dGetTotAllSedThickness()
double CGeomCell::dGetTotAllSedThickness (void) const
Returns the total thickness of all sediment on this cell.
Definition at line 452 of file cell.cpp.
dGetTotBeachDeposition()
double CGeomCell::dGetTotBeachDeposition (void) const
Get beach erosion.
Definition at line 800 of file cell.cpp.
dGetTotCliffCollapse()
double CGeomCell::dGetTotCliffCollapse (void) const
Returns the running total depth of cliff collapse on this cell.
Definition at line 716 of file cell.cpp.
dGetTotCliffCollapseDeposition()
double CGeomCell::dGetTotCliffCollapseDeposition (void) const
Returns the total depth of cliff deposition collapse on this cell.
Definition at line 735 of file cell.cpp.
dGetTotConsThickness()
double CGeomCell::dGetTotConsThickness (void) const
Returns the total thickness of consolidated sediment on this cell.
Definition at line 432 of file cell.cpp.
Referenced by dGetTotAllSedThickness().
dGetTotPotentialBeachErosion()
double CGeomCell::dGetTotPotentialBeachErosion (void) const
Get total potential (unconstrained) beach erosion.
Definition at line 755 of file cell.cpp.
dGetTotPotentialPlatformErosion()
double CGeomCell::dGetTotPotentialPlatformErosion (void) const
Get total potential (unconstrained) shore platform erosion.
Definition at line 539 of file cell.cpp.
dGetTotSeaDepth()
double CGeomCell::dGetTotSeaDepth (void) const
Definition at line 301 of file cell.cpp.
dGetTotSuspendedSediment()
double CGeomCell::dGetTotSuspendedSediment (void) const
Definition at line 320 of file cell.cpp.
dGetTotUnconsThickness()
double CGeomCell::dGetTotUnconsThickness (void) const
Returns the total thickness of unconsolidated sediment on this cell.
Definition at line 442 of file cell.cpp.
Referenced by dGetTotAllSedThickness().
dGetTotWaveHeight()
double CGeomCell::dGetTotWaveHeight (void) const
Returns the total wave height on this cell.
Definition at line 620 of file cell.cpp.
dGetTotWaveOrientation()
double CGeomCell::dGetTotWaveOrientation (void) const
Returns the total wave orientation on this cell.
Definition at line 639 of file cell.cpp.
dGetUnconsD50()
double CGeomCell::dGetUnconsD50 (void) const
Returns the D50 of unconsolidated sediment on this cell.
Definition at line 822 of file cell.cpp.
dGetVolEquivSedTopElev()
double CGeomCell::dGetVolEquivSedTopElev (void) const
Returns the volume-equivalent elevation of the sediment's top surface for this cell (if there is a cliff notch, then lower the elevation by the notch's volume)
Definition at line 376 of file cell.cpp.
dGetWaveHeight()
double CGeomCell::dGetWaveHeight (void) const
Returns the wave height on this cell.
Definition at line 614 of file cell.cpp.
dGetWaveOrientation()
double CGeomCell::dGetWaveOrientation (void) const
Returns the wave orientation on this cell.
Definition at line 633 of file cell.cpp.
dGetWavePeriod()
double CGeomCell::dGetWavePeriod (void) const
IncrBeachDeposition()
void CGeomCell::IncrBeachDeposition (double const dThisDeposition)
Increment this-timestep beach deposition, also increment total beach deposition.
Definition at line 787 of file cell.cpp.
IncrCliffCollapse()
void CGeomCell::IncrCliffCollapse (double const dDepth)
Increments the depth of this-timestep cliff collapse on this cell, also increments the total.
Definition at line 703 of file cell.cpp.
IncrCliffCollapseDeposition()
void CGeomCell::IncrCliffCollapseDeposition (double const dDepth)
Increments the depth of this-timestep cliff deposition collapse on this cell, also increments the total.
Definition at line 722 of file cell.cpp.
InitCell()
void CGeomCell::InitCell (void)
Initialise several values for this cell.
Definition at line 572 of file cell.cpp.
nGetBoundingBoxEdge()
int CGeomCell::nGetBoundingBoxEdge (void) const
Definition at line 86 of file cell.cpp.
nGetDownDriftZoneNumber()
int CGeomCell::nGetDownDriftZoneNumber (void) const
Definition at line 247 of file cell.cpp.
nGetInterventionClass()
int CGeomCell::nGetInterventionClass (void) const
Gets the intervention class.
Definition at line 843 of file cell.cpp.
nGetLayerAtElev()
int CGeomCell::nGetLayerAtElev (double const dElev) const
Given an elevation, this finds the index of the layer that contains that elevation (layer 0 being the first above the basement). Note that the elevation cannot exactly equal the elevation of the layer's top surface (this causes problems with e.g. cliff notches, which extend above this elevation)
Returns ELEV_IN_BASEMENT if in basement, ELEV_ABOVE_SEDIMENT_TOP if higher than or equal to sediment top, or layer number (0 to n),
Definition at line 498 of file cell.cpp.
nGetPolygonID()
int CGeomCell::nGetPolygonID (void) const
Returns the global ID number of the polygon which 'contains' this cell (returns INT_NODATA if the cell is not 'in' a polygon)
Definition at line 210 of file cell.cpp.
nGetProfile()
int CGeomCell::nGetProfile (void) const
If this cell is 'under' a coastline-normal profile, returns the number of the profile. Otherwise it returns INT_NODATA.
Definition at line 189 of file cell.cpp.
nGetShadowZoneNumber()
int CGeomCell::nGetShadowZoneNumber (void) const
Definition at line 221 of file cell.cpp.
nGetTopLayerAboveBasement()
int CGeomCell::nGetTopLayerAboveBasement (void) const
Returns the index of the topmost sediment layer (layer 0 being the one just above basement), which could have zero thickness.
Definition at line 342 of file cell.cpp.
nGetTopNonZeroLayerAboveBasement()
int CGeomCell::nGetTopNonZeroLayerAboveBasement (void) const
Returns the index of the topmost sediment layer (layer 0 being the one just above basement) with non-zero thickness. If there is no such layer, it returns NO_NONZERO_THICKNESS_LAYERS.
Definition at line 326 of file cell.cpp.
pGetLandform()
CRWCellLandform * CGeomCell::pGetLandform (void)
Returns a pointer to this cell's CRWCellLandform object.
Definition at line 254 of file cell.cpp.
pGetLayerAboveBasement()
CRWCellLayer * CGeomCell::pGetLayerAboveBasement (int const nLayer)
Return a reference to the Nth sediment layer (layer 0 being just above basement)
Definition at line 369 of file cell.cpp.
SetActualBeachErosion()
void CGeomCell::SetActualBeachErosion (double const dThisActualErosion)
Set this-timestep actual (constrained) beach erosion and increment total actual beach erosion.
Definition at line 761 of file cell.cpp.
SetActualBeachErosionEstimated()
void CGeomCell::SetActualBeachErosionEstimated (void)
Definition at line 108 of file cell.cpp.
SetActualPlatformErosion()
void CGeomCell::SetActualPlatformErosion (double const dThisActualErosion)
Set this-timestep actual (constrained) shore platform erosion and increment total actual shore platform erosion.
Definition at line 545 of file cell.cpp.
SetAsCoastline()
void CGeomCell::SetAsCoastline (bool const bNewFlag)
Marks this cell as 'under' a coastline.
Definition at line 170 of file cell.cpp.
SetBasementElev()
void CGeomCell::SetBasementElev (double const dNewElev)
Sets this cell's basement elevation.
Definition at line 274 of file cell.cpp.
SetBeachProtectionFactor()
void CGeomCell::SetBeachProtectionFactor (double const dFactor)
Definition at line 690 of file cell.cpp.
SetBoundingBoxEdge()
void CGeomCell::SetBoundingBoxEdge (int const nDirection)
Definition at line 81 of file cell.cpp.
SetDeepWaterWaveHeight()
void CGeomCell::SetDeepWaterWaveHeight (double const dWaveHeight)
Sets the deep water wave height on this cell.
Definition at line 645 of file cell.cpp.
SetDeepWaterWaveOrientation()
void CGeomCell::SetDeepWaterWaveOrientation (double const dWaveOrientation)
Sets the deep water wave orientation on this cell.
Definition at line 657 of file cell.cpp.
SetDeepWaterWavePeriod()
void CGeomCell::SetDeepWaterWavePeriod (double const dWavePeriod)
Sets the deep water wave Period on this cell.
Definition at line 669 of file cell.cpp.
SetDownDriftZoneNumber()
void CGeomCell::SetDownDriftZoneNumber (int const nCode)
Definition at line 242 of file cell.cpp.
SetInActiveZone()
void CGeomCell::SetInActiveZone (bool const bFlag)
Sets a flag to show whether this cell is in the active zone.
Definition at line 120 of file cell.cpp.
SetInContiguousSea()
void CGeomCell::SetInContiguousSea (void)
Definition at line 97 of file cell.cpp.
SetInterventionClass()
void CGeomCell::SetInterventionClass (int const nSubCatCode)
Sets the landform category and subcategory for an intervention.
Definition at line 829 of file cell.cpp.
SetInterventionHeight()
void CGeomCell::SetInterventionHeight (double const dHeight)
Sets the intervention height.
Definition at line 859 of file cell.cpp.
SetLocalConsSlope()
void CGeomCell::SetLocalConsSlope (double const dNewSlope)
Sets the local slope of the consolidated sediment only.
Definition at line 261 of file cell.cpp.
SetPolygonID()
void CGeomCell::SetPolygonID (int const nPolyID)
Sets the global ID number of the polygon which 'contains' this cell.
Definition at line 204 of file cell.cpp.
SetPossibleCoastStartCell()
void CGeomCell::SetPossibleCoastStartCell (void)
Sets a flag to show that this cell has been flagged as a possible start- or end-point for a coastline.
Definition at line 146 of file cell.cpp.
SetPotentialBeachErosion()
void CGeomCell::SetPotentialBeachErosion (double const dPotentialIn)
Set potential (unconstrained) beach erosion and increment total beach potential erosion.
Definition at line 742 of file cell.cpp.
SetPotentialPlatformErosion()
void CGeomCell::SetPotentialPlatformErosion (double const dPotentialIn)
Set potential (unconstrained) shore platform erosion and increment total shore platform potential erosion.
Definition at line 526 of file cell.cpp.
SetProfile()
void CGeomCell::SetProfile (int const nNormal)
Marks this cell as 'under' a coastline-normal profile.
Definition at line 182 of file cell.cpp.
SetSeaDepth()
void CGeomCell::SetSeaDepth (void)
Returns the depth of seawater on this cell if the sediment top is < SWL, or zero.
Definition at line 565 of file cell.cpp.
SetShadowZoneBoundary()
void CGeomCell::SetShadowZoneBoundary (void)
Sets a flag to show that this cell is a shadow zone boundary.
Definition at line 133 of file cell.cpp.
SetShadowZoneNumber()
void CGeomCell::SetShadowZoneNumber (int const nCode)
Definition at line 216 of file cell.cpp.
SetSuspendedSediment()
void CGeomCell::SetSuspendedSediment (double const dNewSedDepth)
Sets this cell's suspended sediment depth equivalent, it also increments the running total of suspended sediment depth equivalent.
Definition at line 307 of file cell.cpp.
SetWaveHeight()
void CGeomCell::SetWaveHeight (double const dWaveHeight)
Sets the wave height on this cell, also increments the total wave height.
Definition at line 604 of file cell.cpp.
SetWaveOrientation()
void CGeomCell::SetWaveOrientation (double const dWaveOrientation)
Sets the wave orientation on this cell, also increments the total wave orientation.
Definition at line 626 of file cell.cpp.
SetWavePeriod()
void CGeomCell::SetWavePeriod (double const)
SetWaveValuesToDeepWaterWaveValues()
void CGeomCell::SetWaveValuesToDeepWaterWaveValues (void)
Sets wave height to the deep water wave height value, and sets wave orientation to the deep water wave orientation value.
Definition at line 681 of file cell.cpp.
Friends And Related Function Documentation
CSimulation
friend class CSimulation friend
Definition at line 37 of file cell.h.
Field Documentation
m_pGrid
CGeomRasterGrid * CGeomCell::m_pGrid = NULL static
Definition at line 96 of file cell.h.
Referenced by bBasementElevIsMissingValue(), bIsInundated(), bIsSeaIncBeach(), CalcAllLayerElevsAndD50(), CGeomRasterGrid::nCreateGrid(), and SetSeaDepth().
The documentation for this class was generated from the following files:
cell.h
cell.cpp
raster_grid.cpp