CoastalME (Coastal Modelling Environment): CGeom2DIPoint Class Reference
CGeom2DIPoint Class Reference
Geometry class used to represent 2D point objects with integer co-ordinates.
#include <2di_point.h>
Public Member Functions
CGeom2DIPoint (void)
Constructor with no parameters (the X and Y co-ordinates of the CGeom2DIPoint object are set to zero)
CGeom2DIPoint (int const, int const)
Constructor with two integer parameters, for the X and Y co-ordinates of the CGeom2DIPoint object.
int nGetX (void) const
Returns the CGeom2DIPoint object's integer X co-ordinate.
int nGetY (void) const
Returns the CGeom2DIPoint object's integer Y co-ordinate.
int * pnGetX ()
Returns a reference to the CGeom2DIPoint object's integer X co-ordinate.
int * pnGetY ()
Returns a reference to the CGeom2DIPoint object's integer Y co-ordinate.
void SetX (int const)
The integer parameter sets a value for the CGeom2DIPoint object's X co-ordinate.
void SetY (int const)
The integer parameter sets a value for the CGeom2DIPoint object's Y co-ordinate.
void SetXY (int const, int const)
The two integer parameters set values for the CGeom2DIPoint object's X and Y co-ordinates.
void AddXAddY (int const, int const)
The parameter is a pointer to a CGeom2DIPoint object, this is used to set values for the CGeom2DIPoint object's X and Y co-ordinates.
void AddXAddY (double const, double const)
Adds the first double parameter (rounded) to the CGeom2DIPoint object's X co-ordinate, adds the second double parameter (rounded) to the CGeom2DIPoint object's Y co-ordinate.
void DivXDivY (double const, double const)
Divides the CGeom2DIPoint object's X co-ordinate by the first double parameter (rounded), divides the CGeom2DIPoint object's Y co-ordinate by the second double parameter (rounded)
void operator= (CGeom2DIPoint *)
Sets one CGeom2DIPoint object to be the same as another.
bool operator== (CGeom2DIPoint *) const
Compares two CGeom2DIPoint objects for equality.
bool operator== (CGeom2DIPoint) const
Compares two CGeom2DIPoint objects for equality.
bool operator!= (CGeom2DIPoint *) const
Compares two CGeom2DIPoint objects for inequality.
bool operator!= (CGeom2DIPoint) const
Compares two CGeom2DIPoint objects for inequality.
Detailed Description
Geometry class used to represent 2D point objects with integer co-ordinates.
The CGeom2DIPoint geometry class is used to represent 2D points where the x and y co-ordinates can only be integer values, e.g. points for which the x and y co-ordinates are in the raster-grid CRS (co-ordinate reference system)
Author
David Favis-Mortlock
Andres Payo
Date
2020
Copyright
GNU General Public License
Definition at line 29 of file 2di_point.h.
Constructor & Destructor Documentation
CGeom2DIPoint() [1/2]
CGeom2DIPoint::CGeom2DIPoint (void)
Constructor with no parameters (the X and Y co-ordinates of the CGeom2DIPoint object are set to zero)
Definition at line 29 of file 2di_point.cpp.
CGeom2DIPoint() [2/2]
CGeom2DIPoint::CGeom2DIPoint (int const nNewX, int const nNewY)
Constructor with two integer parameters, for the X and Y co-ordinates of the CGeom2DIPoint object.
Definition at line 36 of file 2di_point.cpp.
Member Function Documentation
AddXAddY() [1/2]
void CGeom2DIPoint::AddXAddY (double const dXToAdd, double const dYToAdd)
Adds the first double parameter (rounded) to the CGeom2DIPoint object's X co-ordinate, adds the second double parameter (rounded) to the CGeom2DIPoint object's Y co-ordinate.
Definition at line 102 of file 2di_point.cpp.
AddXAddY() [2/2]
void CGeom2DIPoint::AddXAddY (int const nXToAdd, int const nYToAdd)
The parameter is a pointer to a CGeom2DIPoint object, this is used to set values for the CGeom2DIPoint object's X and Y co-ordinates.
Adds the first integer parameter to the CGeom2DIPoint object's X co-ordinate, adds the second integer parameter to the CGeom2DIPoint object's Y co-ordinate
Definition at line 95 of file 2di_point.cpp.
DivXDivY()
void CGeom2DIPoint::DivXDivY (double const dXDiv, double const dYDiv)
Divides the CGeom2DIPoint object's X co-ordinate by the first double parameter (rounded), divides the CGeom2DIPoint object's Y co-ordinate by the second double parameter (rounded)
Definition at line 110 of file 2di_point.cpp.
nGetX()
int CGeom2DIPoint::nGetX (void) const
Returns the CGeom2DIPoint object's integer X co-ordinate.
Definition at line 44 of file 2di_point.cpp.
Referenced by CRWCoast::nGetCoastPointGivenCell(), operator!=(), operator=(), and operator==().
nGetY()
int CGeom2DIPoint::nGetY (void) const
Returns the CGeom2DIPoint object's integer Y co-ordinate.
Definition at line 50 of file 2di_point.cpp.
Referenced by CRWCoast::nGetCoastPointGivenCell(), operator!=(), operator=(), and operator==().
operator!=() [1/2]
bool CGeom2DIPoint::operator!= (CGeom2DIPoint * pPti) const
Compares two CGeom2DIPoint objects for inequality.
Definition at line 151 of file 2di_point.cpp.
operator!=() [2/2]
bool CGeom2DIPoint::operator!= (CGeom2DIPoint Pti) const
Compares two CGeom2DIPoint objects for inequality.
Definition at line 160 of file 2di_point.cpp.
operator=()
void CGeom2DIPoint::operator= (CGeom2DIPoint * pPti)
Sets one CGeom2DIPoint object to be the same as another.
Definition at line 126 of file 2di_point.cpp.
operator==() [1/2]
bool CGeom2DIPoint::operator== (CGeom2DIPoint * pPti) const
Compares two CGeom2DIPoint objects for equality.
Definition at line 133 of file 2di_point.cpp.
operator==() [2/2]
bool CGeom2DIPoint::operator== (CGeom2DIPoint Pti) const
Compares two CGeom2DIPoint objects for equality.
Definition at line 142 of file 2di_point.cpp.
pnGetX()
int * CGeom2DIPoint::pnGetX ()
Returns a reference to the CGeom2DIPoint object's integer X co-ordinate.
Definition at line 56 of file 2di_point.cpp.
pnGetY()
int * CGeom2DIPoint::pnGetY ()
Returns a reference to the CGeom2DIPoint object's integer Y co-ordinate.
Definition at line 62 of file 2di_point.cpp.
SetX()
void CGeom2DIPoint::SetX (int const nNewX)
The integer parameter sets a value for the CGeom2DIPoint object's X co-ordinate.
Definition at line 68 of file 2di_point.cpp.
SetXY()
void CGeom2DIPoint::SetXY (int const nNewX, int const nNewY)
The two integer parameters set values for the CGeom2DIPoint object's X and Y co-ordinates.
Definition at line 80 of file 2di_point.cpp.
SetY()
void CGeom2DIPoint::SetY (int const nNewY)
The integer parameter sets a value for the CGeom2DIPoint object's Y co-ordinate.
Definition at line 74 of file 2di_point.cpp.
The documentation for this class was generated from the following files:
2di_point.h
2di_point.cpp