CoastalME (Coastal Modelling Environment): CSimulation Class Reference
CSimulation Class Reference
This class runs CoastalME simulations.
#include <simulation.h>
Public Member Functions
CSimulation (void)
~CSimulation (void)
double dGetMissingValue (void) const
Returns the NODATA value.
double dGetThisTimestepSWL (void) const
Returns this timestep's still water level.
double dGetMaxBeachElevAboveSWL (void) const
Returns the vertical tolerance for beach cells to be included in smoothing.
int nGetGridXMax (void) const
Returns the cell size.
int nGetGridYMax (void) const
Returns the size of the grid in the Y direction.
double dGetD50Fine (void) const
Returns the global d50 value for fine sediment.
double dGetD50Sand (void) const
Returns the global d50 value for sand sediment.
double dGetD50Coarse (void) const
Returns the global d50 value for coarse sediment.
int nDoSimulation (int, char *[])
Runs the simulation.
void DoSimulationEnd (int const)
Carries out end-of-simulation tidying (error messages etc.)
Data Fields
ofstream LogStream
Detailed Description
This class runs CoastalME simulations.
TODO This is a more detailed description of the CSimulation class
Author
David Favis-Mortlock
Andres Payo
Date
2020
Copyright
GNU General Public License
Definition at line 62 of file simulation.h.
Constructor & Destructor Documentation
CSimulation()
CSimulation::CSimulation (void)
Definition at line 46 of file simulation.cpp.
~CSimulation()
CSimulation::~CSimulation (void)
Definition at line 358 of file simulation.cpp.
Member Function Documentation
dGetD50Coarse()
double CSimulation::dGetD50Coarse (void) const
Returns the global d50 value for coarse sediment.
Definition at line 462 of file simulation.cpp.
Referenced by CGeomCell::CalcAllLayerElevsAndD50().
dGetD50Fine()
double CSimulation::dGetD50Fine (void) const
Returns the global d50 value for fine sediment.
Definition at line 452 of file simulation.cpp.
Referenced by CGeomCell::CalcAllLayerElevsAndD50().
dGetD50Sand()
double CSimulation::dGetD50Sand (void) const
Returns the global d50 value for sand sediment.
Definition at line 457 of file simulation.cpp.
Referenced by CGeomCell::CalcAllLayerElevsAndD50().
dGetMaxBeachElevAboveSWL()
double CSimulation::dGetMaxBeachElevAboveSWL (void) const
Returns the vertical tolerance for beach cells to be included in smoothing.
Definition at line 432 of file simulation.cpp.
dGetMissingValue()
double CSimulation::dGetMissingValue (void) const
Returns the NODATA value.
Definition at line 420 of file simulation.cpp.
dGetThisTimestepSWL()
double CSimulation::dGetThisTimestepSWL (void) const
Returns this timestep's still water level.
Definition at line 426 of file simulation.cpp.
DoSimulationEnd()
void CSimulation::DoSimulationEnd (int const nRtn)
Carries out end-of-simulation tidying (error messages etc.)
Definition at line 2203 of file utils.cpp.
Referenced by main().
nDoSimulation()
int CSimulation::nDoSimulation (int nArg, char * pcArgv[])
Runs the simulation.
Definition at line 473 of file simulation.cpp.
Referenced by main().
nGetGridXMax()
int CSimulation::nGetGridXMax (void) const
Returns the cell size.
Returns the size of the grid in the X direction
Definition at line 442 of file simulation.cpp.
Referenced by CGeomRasterGrid::nCreateGrid(), and CGeomRasterGrid::~CGeomRasterGrid().
nGetGridYMax()
int CSimulation::nGetGridYMax (void) const
Returns the size of the grid in the Y direction.
Definition at line 447 of file simulation.cpp.
Referenced by CGeomRasterGrid::nCreateGrid().
Field Documentation
LogStream
ofstream CSimulation::LogStream
Definition at line 758 of file simulation.h.
Referenced by DoSimulationEnd(), nDoSimulation(), and ~CSimulation().
The documentation for this class was generated from the following files:
simulation.h
assign_landforms.cpp
calc_curvature.cpp
calc_external_forcing.cpp
calc_shadow_zones.cpp
calc_waves.cpp
create_polygons.cpp
create_profiles.cpp
do_beach_actual_sediment_movement.cpp
do_beach_estimate_actual_erosion.cpp
do_beach_potential_erosion.cpp
do_beach_within_polygon.cpp
do_cliff_collapse.cpp
do_intervention.cpp
gis_raster.cpp
gis_utils.cpp
gis_vector.cpp
init_grid.cpp
locate_coast.cpp
locate_estuaries.cpp
random_numbers.cpp
read_input.cpp
shore_platform.cpp
simulation.cpp
smooth_line.cpp
update_grid.cpp
utils.cpp
write_output.cpp